// Based on mosh (https://github.com/mobile-shell/mosh)
// Copyright 2012 Keith Winstein
// License: GPL-3.0-or-later
// Modified: flattened extensions for prost compatibility

syntax = "proto2";

option optimize_for = LITE_RUNTIME;

package ClientBuffers;

message UserMessage {
  repeated Instruction instruction = 1;
}

message Instruction {
  optional Keystroke keystroke = 2;
  optional ResizeMessage resize = 3;
}

message Keystroke {
  optional bytes keys = 4;
}

message ResizeMessage {
  optional int32 width = 5;
  optional int32 height = 6;
}
